---
language: ruby
cache: bundler
install: "bundle install --jobs=3 --retry=3"
script: "bundle exec cucumber -ptravis features"
rvm:
  - 2.4.0
  - 2.5.9
  - 2.6.
  - 2.7.2
  - rbx
  - rbx-19mode
  - ree

