---
language: ruby
install: "bundle install --jobs=3 --retry=3"
script: "bundle exec cucumber -ptravis features"
before_install:
  - yes | gem update --system --force
  - gem install bundler
rvm:
  - 2.6
  - 2.7.3
  - 3.0.1
